name: Container Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
   Build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: acr1356.azurecr.io
          username: "70b9df21-12ec-4d0e-93f9-52a64180733f"
          password: "F_h8Q~a0glnso7GSILReEdbkwm0uCNgH_MP1rdaK"
    
      - run: |
          docker build ./BlazorApp1 -t acr1356.azurecr.io/myapp:v2
          docker push acr1356.azurecr.io/myapp:v2  

