name: Container Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
   Build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: acr1356.azurecr.io
          username: acr1356
          password: 3NGS6Zt4ZNHIpD/N7xHoZGkh/Au6KCbbaTwQf8dTvL+ACRBDNk6z
    
      - run: |
          docker build ./BlazorApp1 -t acr1356.azurecr.io/myapp:v1
          docker push acr1356.azurecr.io/myapp:v1   
      
     
