name: Aks Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
   Build:
    
     runs-on: ubuntu-latest
     env:
       jobenv1: "jobe11111"
     steps:
       -  name: step1 
          run: |
            lol="loleeeee"
            echo $AZURE_WEBAPP_NAME
            AZURE_WEBAPP_NAME="thomas"
            echo $AZURE_WEBAPP_NAME
            echo $lol
            echo $jobenv1
       -  name: step2
          env:
            hello: "HHHHHHHH"
       -  name: steps23 
          run: |
             echo $AZURE_WEBAPP_NAME
             echo $lol
             echo $jobenv1
             echo $hello
