name: Container Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
   Build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2 
    
     
      - name: SonarCloud Scan
        
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        with:
          projectBaseDir: ./BlazorApp1       
  
