name: Container Pipeline

on:
  workflow_dispatch:



jobs:
   Build:
     runs-on: [self-hosted,Linux]
     steps:
      - uses: actions/checkout@v2
   
     
      - name: SonarCloud Scan
        
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        with:
          projectBaseDir: ./BlazorApp1       
   
     
