name: Container Pipeline

on:
  workflow_dispatch:

jobs:
   sql:
     runs-on: [self-hosted]
     services:
       sql:
         image: mcr.microsoft.com/mssql/server:2022-latest  
         ports: 
           - 1440:1440

       redis:
         image: redis
         ports:
           - 6379:6379
         
           
    

