name: Container Pipeline

on:
  workflow_dispatch:

jobs:
   sql:
     runs-on: [self-hosted, Linux]
     services:
      # sql1:
       #  image: mcr.microsoft.com/mssql/server:2022-latest  
        # ports: 
         #  - 1440:1440

       redis:
         image: redis
         ports:
           - 6379:6379

     steps:
       - name: shell
         shell: pwsh
         run: get-process
         
           
    

