name: Tests

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
             client-id:  "1b648961-aabc-49fb-96be-5436e0038d7c"
             tenant-id:  "58bade9d-b753-4cdd-bea4-6183f95a1ce5"
             subscription-id: "02cd8bbf-2d3c-4eed-9c95-cf75af7acd37"
             enable-AzPSSession: true

      - name: HashiCorp - Setup Terraform
  # You may pin to the exact commit or the version.
  # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        uses: hashicorp/setup-terraform@v2.0.3
  
