name: My Test2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          $user="tzebar@thomaszebargmail.onmicrosoft.com"
          
          
    
