name: Tests

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
    # Specify the Az PowerShell script here.
         inlineScript: |
           get-process
           write-host " hello Thomas"
    # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
         azPSVersion: 7.3.0
    # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
    
