name: Tests

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
   AZURE_WEBAPP_NAME: app1356
   AZURE_WEBAPP_PACKAGE_PATH: .
   DOTNET_VERSION: 6.0.x

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with:
    # Specify the script here
         inlineScript: |
           $x= " I am kkkkk"
           az $x
   
